
import { Creator, Job, User, UserRole } from './types';

export const INITIAL_CREATORS: Creator[] = [
  {
    id: 'c1',
    fullName: 'Arjun Mehta',
    email: 'arjun@example.com',
    city: 'Mumbai',
    skills: ['UI/UX Design', 'Brand Identity', 'Illustration'],
    purchasedTags: ['UI/UX Design'],
    bio: 'Passionate designer with 5+ years of experience in creating digital products that matter.',
    experience: 'Previously worked at Tech Giants and Boutique Agencies.',
    profilePhoto: 'https://picsum.photos/seed/arjun/400/400',
    portfolio: [
      { id: 'p1', type: 'image', url: 'https://picsum.photos/seed/p1/800/600', title: 'Brand Revamp' },
      { id: 'p2', type: 'image', url: 'https://picsum.photos/seed/p2/800/600', title: 'Mobile App' },
    ],
    whatsapp: '919876543210',
    isFeatured: true,
    tier: 'PLATINUM',
    status: 'APPROVED',
  },
  {
    id: 'c2',
    fullName: 'Sara Khan',
    email: 'sara@example.com',
    city: 'Bangalore',
    skills: ['Content Writing', 'SEO', 'Copywriting'],
    purchasedTags: [],
    bio: 'Wordsmith helping brands tell their stories through engaging and high-ranking content.',
    experience: 'Ex-Journalist and Freelance Content Strategist.',
    profilePhoto: 'https://picsum.photos/seed/sara/400/400',
    portfolio: [],
    whatsapp: '919888877777',
    isFeatured: false,
    tier: 'BASE',
    status: 'APPROVED',
  },
  {
    id: 'c3',
    fullName: 'Vikram Singh',
    email: 'vikram@example.com',
    city: 'Delhi',
    skills: ['Video Editing', 'Motion Graphics', 'Cinematography'],
    purchasedTags: ['Video Editing'],
    bio: 'Cinematographer and editor specializing in high-energy commercial videos and documentaries.',
    experience: '8 years in the film industry.',
    profilePhoto: 'https://picsum.photos/seed/vikram/400/400',
    portfolio: [
      { id: 'v1', type: 'video', url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', title: 'Showreel 2023' }
    ],
    whatsapp: '919000011111',
    isFeatured: true,
    tier: 'GOLD',
    status: 'APPROVED',
  },
  {
    id: 'c4',
    fullName: 'Hubaib Khan',
    email: 'hubaib@example.com',
    city: 'Indore',
    skills: ['Video Editing', 'Logo Creator', 'Cinematography'],
    purchasedTags: ['Video Editor', 'Logo Creator'],
    bio: 'Visual storyteller based in Indore. Specializing in high-impact video production and minimalist logo design.',
    experience: 'Freelancing for international clients for 4 years.',
    profilePhoto: 'https://picsum.photos/seed/hubaib/400/400',
    portfolio: [],
    whatsapp: '917000123456',
    isFeatured: true,
    tier: 'PLATINUM',
    status: 'APPROVED',
  },
  {
    id: 'c5',
    fullName: 'Meera Iyer',
    email: 'meera@example.com',
    city: 'Chennai',
    skills: ['Graphic Design', 'Package Design'],
    purchasedTags: [],
    bio: 'Minimalist designer focusing on eco-friendly packaging and brand aesthetics.',
    experience: 'Worked with top FMCG brands in India.',
    profilePhoto: 'https://picsum.photos/seed/meera/400/400',
    portfolio: [],
    whatsapp: '919900887766',
    isFeatured: false,
    tier: 'GOLD',
    status: 'APPROVED',
  },
  {
    id: 'c6',
    fullName: 'Rohan Joshi',
    email: 'rohan@example.com',
    city: 'Pune',
    skills: ['Web Development', 'React', 'Node.js'],
    purchasedTags: [],
    bio: 'Full stack developer building performant web applications.',
    experience: '3 years at a tech startup.',
    profilePhoto: 'https://picsum.photos/seed/rohan/400/400',
    portfolio: [],
    whatsapp: '918800112233',
    isFeatured: false,
    tier: 'BASE',
    status: 'APPROVED',
  },
  {
    id: 'c7',
    fullName: 'Ananya Roy',
    email: 'ananya@example.com',
    city: 'Kolkata',
    skills: ['Photography', 'Digital Art'],
    purchasedTags: ['Digital Art'],
    bio: 'Fine art photographer and digital illustrator exploring the intersection of reality and dreams.',
    experience: 'Exhibited in 3 national galleries.',
    profilePhoto: 'https://picsum.photos/seed/ananya/400/400',
    portfolio: [],
    whatsapp: '917766554433',
    isFeatured: true,
    tier: 'PLATINUM',
    status: 'APPROVED',
  },
  {
    id: 'c8',
    fullName: 'Ishan Gupta',
    email: 'ishan@example.com',
    city: 'Mumbai',
    skills: ['Music Production', 'Sound Design'],
    purchasedTags: [],
    bio: 'Crafting unique sonic identities for brands and films.',
    experience: 'Produced soundtracks for several award-winning short films.',
    profilePhoto: 'https://picsum.photos/seed/ishan/400/400',
    portfolio: [],
    whatsapp: '919555443322',
    isFeatured: false,
    tier: 'BASE',
    status: 'APPROVED',
  },
  {
    id: 'c9',
    fullName: 'Zoya Ahmed',
    email: 'zoya@example.com',
    city: 'Hyderabad',
    skills: ['3D Modeling', 'Character Design'],
    purchasedTags: ['3D Modeling'],
    bio: '3D artist with a passion for character creation and environmental design.',
    experience: 'Lead artist at a gaming studio.',
    profilePhoto: 'https://picsum.photos/seed/zoya/400/400',
    portfolio: [],
    whatsapp: '919222334455',
    isFeatured: false,
    tier: 'GOLD',
    status: 'APPROVED',
  },
  {
    id: 'c10',
    fullName: 'Kabir Das',
    email: 'kabir@example.com',
    city: 'Ahmedabad',
    skills: ['App Development', 'Flutter'],
    purchasedTags: [],
    bio: 'Building smooth mobile experiences across platforms.',
    experience: 'Developed and published 5+ apps on Play Store.',
    profilePhoto: 'https://picsum.photos/seed/kabir/400/400',
    portfolio: [],
    whatsapp: '919111223344',
    isFeatured: false,
    tier: 'BASE',
    status: 'APPROVED',
  },
  {
    id: 'c11',
    fullName: 'Aisha Verma',
    email: 'aisha@example.com',
    city: 'Indore',
    skills: ['Web Developer', 'UI Design'],
    purchasedTags: ['Web Developer'],
    bio: 'Frontend enthusiast creating pixel-perfect interfaces in the heart of MP.',
    experience: 'Ex-Amazon intern, now full-time freelancer.',
    profilePhoto: 'https://picsum.photos/seed/aisha/400/400',
    portfolio: [],
    whatsapp: '919000554433',
    isFeatured: true,
    tier: 'PLATINUM',
    status: 'APPROVED',
  },
  {
    id: 'c12',
    fullName: 'Raghav Sharma',
    email: 'raghav@example.com',
    city: 'Jaipur',
    skills: ['Social Media Designer', 'Branding'],
    purchasedTags: ['Social Media Designer'],
    bio: 'Helping small businesses grow their social footprint through stunning visuals.',
    experience: 'Managed social presence for 10+ Jaipur-based startups.',
    profilePhoto: 'https://picsum.photos/seed/raghav/400/400',
    portfolio: [],
    whatsapp: '919333445566',
    isFeatured: false,
    tier: 'GOLD',
    status: 'APPROVED',
  },
  {
    id: 'c13',
    fullName: 'Diya Malhotra',
    email: 'diya@example.com',
    city: 'Chandigarh',
    skills: ['Voice Over', 'Podcast Editing'],
    purchasedTags: [],
    bio: 'Professional voice artist with a home studio setup.',
    experience: 'Voice for several regional TV commercials.',
    profilePhoto: 'https://picsum.photos/seed/diya/400/400',
    portfolio: [],
    whatsapp: '919444556677',
    isFeatured: false,
    tier: 'BASE',
    status: 'APPROVED',
  },
  {
    id: 'c14',
    fullName: 'Neil Pereira',
    email: 'neil@example.com',
    city: 'Goa',
    skills: ['Motion Designer', 'VFX'],
    purchasedTags: ['Motion Designer'],
    bio: 'Motion graphics artist bringing static designs to life.',
    experience: 'Created promotional videos for Goa tourism board.',
    profilePhoto: 'https://picsum.photos/seed/neil/400/400',
    portfolio: [],
    whatsapp: '919555667788',
    isFeatured: true,
    tier: 'PLATINUM',
    status: 'APPROVED',
  },
  {
    id: 'c15',
    fullName: 'Sana Sheikh',
    email: 'sana@example.com',
    city: 'Lucknow',
    skills: ['Illustration', 'Concept Art'],
    purchasedTags: ['Illustration'],
    bio: 'Digital illustrator specializing in cultural themes and modern art.',
    experience: 'Illustrator for several children’s books.',
    profilePhoto: 'https://picsum.photos/seed/sana/400/400',
    portfolio: [],
    whatsapp: '919666778899',
    isFeatured: false,
    tier: 'GOLD',
    status: 'APPROVED',
  },
  {
    id: 'c16',
    fullName: 'Amit Kumar',
    email: 'amit@example.com',
    city: 'Patna',
    skills: ['SEO', 'Digital Marketing'],
    purchasedTags: [],
    bio: 'Data-driven marketer helping brands rank higher and reach further.',
    experience: '5 years in digital agency roles.',
    profilePhoto: 'https://picsum.photos/seed/amit/400/400',
    portfolio: [],
    whatsapp: '919777889900',
    isFeatured: false,
    tier: 'BASE',
    status: 'APPROVED',
  },
  {
    id: 'c17',
    fullName: 'Rhea Kapoor',
    email: 'rhea@example.com',
    city: 'Indore',
    skills: ['Social Media Designer', 'Content Strategy'],
    purchasedTags: ['Social Media Designer'],
    bio: 'Strategist and designer for the modern social web.',
    experience: 'Grew client accounts by 300% on average.',
    profilePhoto: 'https://picsum.photos/seed/rhea/400/400',
    portfolio: [],
    whatsapp: '919888990011',
    isFeatured: true,
    tier: 'PLATINUM',
    status: 'APPROVED',
  },
  {
    id: 'c18',
    fullName: 'Vivaan Reddy',
    email: 'vivaan@example.com',
    city: 'Bangalore',
    skills: ['Backend Engineering', 'Python'],
    purchasedTags: [],
    bio: 'Expert in building scalable backend systems and APIs.',
    experience: 'Ex-Flipkart, currently independent consultant.',
    profilePhoto: 'https://picsum.photos/seed/vivaan/400/400',
    portfolio: [],
    whatsapp: '919999001122',
    isFeatured: false,
    tier: 'GOLD',
    status: 'APPROVED',
  },
  {
    id: 'c19',
    fullName: 'Kiara Singh',
    email: 'kiara@example.com',
    city: 'Delhi',
    skills: ['Fashion Styling', 'Creative Direction'],
    purchasedTags: [],
    bio: 'Creative director for editorial shoots and fashion brands.',
    experience: 'Portfolio includes shoots for Vogue India.',
    profilePhoto: 'https://picsum.photos/seed/kiara/400/400',
    portfolio: [],
    whatsapp: '919111334455',
    isFeatured: false,
    tier: 'BASE',
    status: 'APPROVED',
  },
  {
    id: 'c20',
    fullName: 'Aryan Joshi',
    email: 'aryan@example.com',
    city: 'Mumbai',
    skills: ['Motion Designer', 'Logo Creator'],
    purchasedTags: ['Motion Designer', 'Logo Creator'],
    bio: 'Expert at building brands and then setting them in motion.',
    experience: 'Freelance since 2018, worked with 50+ clients.',
    profilePhoto: 'https://picsum.photos/seed/aryan/400/400',
    portfolio: [],
    whatsapp: '919222445566',
    isFeatured: true,
    tier: 'PLATINUM',
    status: 'APPROVED',
  }
];

export const INITIAL_JOBS: Job[] = [
  {
    id: 'j1',
    title: 'Senior Graphic Designer',
    city: 'Remote',
    requiredSkills: ['Adobe Creative Suite', 'Figma'],
    description: 'We are looking for a creative thinker to join our fast-paced marketing team.',
    contactEmail: 'careers@creativeedge.com',
    whatsapp: '919876543210',
    company: 'Creative Edge',
    postedDate: '2023-10-25',
    budget: '₹45,000 / PROJECT',
  },
  {
    id: 'j2',
    title: 'Video Editor (Short Form)',
    city: 'Indore',
    requiredSkills: ['Premiere Pro', 'After Effects'],
    description: 'Looking for a talented editor for daily Reels/TikTok production.',
    contactEmail: 'hr@vlogstudio.in',
    whatsapp: '917000998877',
    company: 'Vlog Studio',
    postedDate: '2023-11-01',
    budget: '₹2,500 / REEL',
  },
  {
    id: 'j3',
    title: 'Full Stack Developer',
    city: 'Bangalore',
    requiredSkills: ['React', 'Node.js', 'PostgreSQL'],
    description: 'Join our early-stage fintech startup to build the next generation of banking.',
    contactEmail: 'tech@payflow.com',
    whatsapp: '918899001122',
    company: 'PayFlow Tech',
    postedDate: '2023-11-02',
    budget: '₹1.2L / MONTH',
  },
  {
    id: 'j4',
    title: 'Motion Graphics Artist',
    city: 'Mumbai',
    requiredSkills: ['After Effects', 'Cinema 4D'],
    description: 'Lead motion designer for an upcoming music video project.',
    contactEmail: 'prod@mumbaimedia.in',
    whatsapp: '919122334455',
    company: 'Mumbai Media Works',
    postedDate: '2023-11-03',
    budget: '₹75,000 / PROJECT',
  },
  {
    id: 'j5',
    title: 'Social Media Manager',
    city: 'Remote',
    requiredSkills: ['Strategy', 'Copywriting', 'Analytics'],
    description: 'Managing a portfolio of 5 lifestyle brands.',
    contactEmail: 'apply@socialscale.com',
    whatsapp: '919555664433',
    company: 'SocialScale Agency',
    postedDate: '2023-11-04',
    budget: '₹40,000 / MONTH',
  },
  {
    id: 'j6',
    title: 'Logo & Identity Designer',
    city: 'Delhi',
    requiredSkills: ['Illustrator', 'Branding'],
    description: 'Contract project for a new boutique hotel chain branding.',
    contactEmail: 'design@hotelgroup.com',
    whatsapp: '919111445566',
    company: 'Heritage Hotels',
    postedDate: '2023-11-05',
    budget: '₹35,000 / PROJECT',
  },
  {
    id: 'j7',
    title: 'React Native Expert',
    city: 'Remote',
    requiredSkills: ['React Native', 'TypeScript'],
    description: 'Fixing bugs and implementing new features for a health-tech app.',
    contactEmail: 'ops@healthplus.io',
    whatsapp: '919000112233',
    company: 'HealthPlus',
    postedDate: '2023-11-06',
    budget: '₹80,000 / MODULE',
  },
  {
    id: 'j8',
    title: 'Content Strategist',
    city: 'Mumbai',
    requiredSkills: ['SEO', 'Content Planning'],
    description: 'Planning content calendar for a luxury real estate portal.',
    contactEmail: 'jobs@estatesmumbai.com',
    whatsapp: '919888776655',
    company: 'Premium Estates',
    postedDate: '2023-11-07',
    budget: '₹55,000 / MONTH',
  },
  {
    id: 'j9',
    title: 'UI Designer',
    city: 'Bangalore',
    requiredSkills: ['Figma', 'Prototyping'],
    description: 'Designing a dashboard for an enterprise SaaS product.',
    contactEmail: 'hr@cloudsync.com',
    whatsapp: '919777553311',
    company: 'CloudSync',
    postedDate: '2023-11-08',
    budget: '₹95,000 / PROJECT',
  },
  {
    id: 'j10',
    title: 'Product Photographer',
    city: 'Hyderabad',
    requiredSkills: ['Photography', 'Lightroom'],
    description: 'Monthly catalog shoots for an e-commerce fashion brand.',
    contactEmail: 'studio@fashionshop.in',
    whatsapp: '919222554433',
    company: 'The Fashion Shop',
    postedDate: '2023-11-09',
    budget: '₹12,000 / DAY',
  },
  {
    id: 'j11',
    title: 'Technical Writer',
    city: 'Pune',
    requiredSkills: ['Documentation', 'API'],
    description: 'Writing developer documentation for a blockchain protocol.',
    contactEmail: 'docs@chaintech.com',
    whatsapp: '919444332211',
    company: 'ChainTech Solutions',
    postedDate: '2023-11-10',
    budget: '₹60,000 / MONTH',
  },
  {
    id: 'j12',
    title: '3D Modeler (Game Assets)',
    city: 'Delhi',
    requiredSkills: ['Blender', 'Unity'],
    description: 'Creating low-poly assets for a mobile RPG game.',
    contactEmail: 'art@gamestudio.com',
    whatsapp: '919000445566',
    company: 'HyperCasual Games',
    postedDate: '2023-11-11',
    budget: '₹50,000 / PACK',
  },
  {
    id: 'j13',
    title: 'Android Developer',
    city: 'Bangalore',
    requiredSkills: ['Kotlin', 'Architecture Components'],
    description: 'Modernizing a legacy Android app with Kotlin and MVVM.',
    contactEmail: 'dev@legacytech.com',
    whatsapp: '919888442200',
    company: 'Legacy Tech',
    postedDate: '2023-11-12',
    budget: '₹1.1L / MONTH',
  },
  {
    id: 'j14',
    title: 'SEO Specialist',
    city: 'Remote',
    requiredSkills: ['Ahrefs', 'Technical SEO'],
    description: 'Improving organic reach for an international blog network.',
    contactEmail: 'seo@blognet.com',
    whatsapp: '919333221100',
    company: 'BlogNet International',
    postedDate: '2023-11-13',
    budget: '₹35,000 / MONTH',
  },
  {
    id: 'j15',
    title: 'Creative Copywriter',
    city: 'Mumbai',
    requiredSkills: ['Ad Copy', 'Storytelling'],
    description: 'Writing scripts and copy for digital ad campaigns.',
    contactEmail: 'creative@adagency.com',
    whatsapp: '919111887766',
    company: 'The Ad Agency',
    postedDate: '2023-11-14',
    budget: '₹20,000 / CAMPAIGN',
  },
  {
    id: 'j16',
    title: 'Children’s Book Illustrator',
    city: 'Kolkata',
    requiredSkills: ['Digital Painting', 'Procreate'],
    description: 'Illustrating a series of 5 educational children’s books.',
    contactEmail: 'books@prakashan.in',
    whatsapp: '919666223344',
    company: 'Ananda Prakashan',
    postedDate: '2023-11-15',
    budget: '₹65,000 / SERIES',
  },
  {
    id: 'j17',
    title: 'Growth Marketing Head',
    city: 'Chennai',
    requiredSkills: ['Paid Ads', 'Funnel Optimization'],
    description: 'Leading the growth team for a food-tech unicorn.',
    contactEmail: 'talent@eatwell.com',
    whatsapp: '919999887766',
    company: 'EatWell',
    postedDate: '2023-11-16',
    budget: '₹2.5L / MONTH',
  },
  {
    id: 'j18',
    title: 'Go Backend Engineer',
    city: 'Remote',
    requiredSkills: ['Golang', 'Kubernetes', 'gRPC'],
    description: 'Building high-performance microservices for a video platform.',
    contactEmail: 'platform@streamer.io',
    whatsapp: '919555001122',
    company: 'Streamer.io',
    postedDate: '2023-11-17',
    budget: '₹1.8L / MONTH',
  },
  {
    id: 'j19',
    title: 'Sound Designer',
    city: 'Mumbai',
    requiredSkills: ['Ableton Live', 'Mixing'],
    description: 'Designing soundscapes for a series of VR experiences.',
    contactEmail: 'vrsound@studio.in',
    whatsapp: '919222001133',
    company: 'VR Studio Mumbai',
    postedDate: '2023-11-18',
    budget: '₹45,000 / SCENE',
  },
  {
    id: 'j20',
    title: 'Creative Director',
    city: 'Delhi',
    requiredSkills: ['Leadership', 'Design Strategy'],
    description: 'Overseeing all creative output for a major automotive brand.',
    contactEmail: 'hr@automotiveagency.com',
    whatsapp: '919111223355',
    company: 'AutoAgency Delhi',
    postedDate: '2023-11-19',
    budget: '₹3L / MONTH',
  }
];

export const INITIAL_USERS: User[] = [
  { id: 'u1', email: 'admin@creatorhub.com', role: UserRole.ADMIN },
  { id: 'u2', email: 'arjun@example.com', role: UserRole.CREATOR, creatorId: 'c1' },
];
